### ISSUE TITLE
RELAP5 code interface

### ISSUE THREAD

**Issue by AaronEpiney** [idaholab/raven#995] opened 2019-05-21 23:04 UTC
--------
Issue Description
--------

The RELAP5 code interface tries to sort dictionaries (RELAPparser.py line 146). This leads to a crush.

----------------
For Change Control Board: Issue Review
----------------
This review should occur before any development is performed as a response to this issue.
- [x] 1. Is it tagged with a type: defect or task?
- [x] 2. Is it tagged with a priority: critical, normal or minor?
- [x] 3. If it will impact requirements or requirements tests, is it tagged with requirements?
- [x] 4. If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users. __Crash, no wrong results__
- [x] 5. Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

-------
For Change Control Board: Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [x] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [x] 5. If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by wangcj05** [comment] 2019-06-24 20:58
Several things  need to be checked before the closure of this issue:
1. Do we test the interface with the crashing?
2. An email should send out to the users
3. I think this issue will also affect the latest release.

@PaulTalbot-INL @alfoa Please let me know what do you think?

**Comment by alfoa** [comment] 2019-06-25 21:55
Regarding the email to the users, It is not needed since no wrong results are caused by the issue but a crash of the external code interface. 
Regarding the other 2 questions, I agree. A test should be added and I am tagging this issue with the tag for the next release.

**Comment by alfoa** [comment] 2019-06-25 21:56
Ref. #988

**Comment by wangcj05** [comment] 2019-10-15 21:55
Currently, the fix in PR #1066 will fix the defect, but there is no good way to test this defect. Test could be added latter when we found a way to test it. In addition, I think this defect is affecting current release. A bug fix/issue should be created for the current release. This is assigned to @alfoa. 
Overall, the checklists are good, and can be closed with PR #1066

**Closed** 2019-10-15 21:56 UTC
Labels: FutureRAVENv2.0, defect, external interfaces, priority_normal
