### ISSUE TITLE
Dymola Tests failing with new libraries

### ISSUE THREAD

**Issue by joshua-cogliati-inl** [idaholab/raven#87] opened 2017-04-06 22:04 UTC
With libraries:
```
numpy 1.12.1
h5py 2.7.0
scipy 0.19.0
sklearn 0.18.1
matplotlib 2.0.0 
```

The tests framework/CodeInterfaceTests.DymolaTestTimeDepNoExecutableEnsembleModel and framework/CodeInterfaceTests.DymolaTestNoExecutable fail.

```
framework/CodeInterfaceTests.DymolaTestTimeDepNoExecutableEnsembleModel FAILED (In DMInterfaceTestTimedep/testDummyStep/BouncingBall++1/out~dsin.csv: The values in column "e" don't match
	rel diff:  0 ~ 0.699999988079 = 1.0
In DMInterfaceTestTimedep/testDummyStep/BouncingBall++1/out~dsin.csv: The values in column "g" don't match
	rel diff:  9.0 ~ 9.81000041962 = 0.082568846582
In DMInterfaceTestTimedep/testDummyStep/BouncingBall++1/out~dsin.csv: The values in column "hstart" don't match
	rel diff:  3.0 ~ 3.53770232201 = 0.151991963445
In DMInterfaceTestTimedep/testDummyStep/BouncingBall++5/out~dsin.csv: The values in column "e" don't match
	rel diff:  0 ~ 0.699999988079 = 1.0
In DMInterfaceTestTimedep/testDummyStep/BouncingBall++5/out~dsin.csv: The values in column "g" don't match
	rel diff:  9.0 ~ 9.81000041962 = 0.082568846582
In DMInterfaceTestTimedep/testDummyStep/BouncingBall++5/out~dsin.csv: The values in column "hstart" don't match
	rel diff:  3.0 ~ 3.53770232201 = 0.151991963445
) (reprint)
```

From: https://hpcgitlab.inl.gov/idaholab/raven/issues/826  
See also: https://hpcsc.inl.gov/ssl/raven_downloads/test_results/2017_Apr_05//log_Ubuntu_14.04_jjc-ubuntu-14-04-conda

**Comment by alfoa** [comment] 2017-04-06 22:50
The problem is scipy. They changed the scipy.io.readmat method that now it reads the values like they are "integers"....

**Comment by alfoa** [comment] 2017-04-06 22:50
This is not a bug of RAVEN but of the Dymola code interface (external entities)

**Comment by alfoa** [comment] 2017-04-07 00:05
I have to correct my self.

Strange. I tried to update the libraries and I do not get any failure...

**Comment by maljovec** [comment] 2017-06-27 01:09
See PR #232. I found the issue. The dtype of np.full is being set to integer in the following line in `DymolaInterface.py`:

```python
Data1Array =  numpy.full((sizeParams,numOutputPts),1)
```

This can be avoided by suggesting the datatype more explicitly with:

```python
Data1Array =  numpy.full((sizeParams,numOutputPts),1.)
```

Notice the period enforces that 1 will be treated as a float not an integer.

**Comment by PaulTalbot-INL** [comment] 2017-06-27 21:53
-------
 Issue Closure
-------
This review should occur when the issue is imminently going to be closed.
- [x] 1. If the issue is a defect, is the defect fixed?
- [x] 2. If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] 3. If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [x] 4. If the issue is a defect, does it impact the latest stable branch? If yes, is there any issue tagged with stable (create if needed)? __n/a__
- [x] 5. If the issue is being closed without a merge request, has an explanation of why it is being closed been provided?

@bobkinl @maljovec does closing this issue warrant an announcement to the Dymola users, or can we push without additional notification?

**Comment by PaulTalbot-INL** [comment] 2017-06-27 22:11
As @AaronEpiney says this change is not disruptive to the current dymola users, we can merge without notification.

**Closed** 2017-06-27 22:11 UTC
Labels: defect, external interfaces, priority_normal
