### ISSUE TITLE
[DEFECT] Raven does not support Python  >3.9 and the dependencies file should reflect it

### ISSUE THREAD

**Issue by aalfonsi** [idaholab/raven#2020] opened 2022-11-23 23:15 UTC
### Thank you for the defect report

- [X] I am using the latest version of `RAVEN`.
- [X] I have read the [Wiki](https://github.com/idaholab/raven/wiki).
- [X] I have created a [minimum, reproducible example](https://stackoverflow.com/help/minimal-reproducible-example)
that demonstrates the defect.

### Defect Description

Raven does not support Python  >3.8 (e.g. Pymo installation failures, etc.) but the dependency file https://github.com/idaholab/raven/blob/devel/dependencies.xml does not reflect that (at least in Mac and linux):

```<python skip_check='True' os='mac,linux'>3</python>```

If the ```establish_conda``` is run, the latest version of python is downloaded (3.11) 

<img width="945" alt="Screen Shot 2022-11-23 at 4 14 18 PM" src="https://user-images.githubusercontent.com/26668536/203661880-49b49337-7007-466a-8f84-d9ba709019fd.png">

### Steps to Reproduce

Fresh installation of RAVEN

### Expected Behavior

No failure in build and installation

### OS

MacOS

### Dependency Manager

CONDA

### For Change Control Board: Issue Review

- [ ] Is it tagged with a type: defect or task?
- [ ] Is it tagged with a priority: critical, normal or minor?
- [ ] If it will impact requirements or requirements tests, is it tagged with requirements?
- [ ] If it is a defect, can it cause wrong results for users? If so an email needs to be sent to the users.
- [X] Is a rationale provided? (Such as explaining why the improvement is needed or why current code is wrong.)

### For Change Control Board: Issue Closure

- [ ] If the issue is a defect, is the defect fixed?
- [ ] If the issue is a defect, is the defect tested for in the regression test system?  (If not explain why not.)
- [ ] If the issue can impact users, has an email to the users group been written (the email should specify if the defect impacts stable or master)?
- [ ] If the issue is a defect, does it impact the latest release branch? If yes, is there any issue tagged with release (create if needed)?
- [ ] If the issue is being closed without a pull request, has an explanation of why it is being closed been provided?

**Comment by aalfonsi** [comment] 2023-02-07 18:28
@joshua-cogliati-inl I see you are playing with the dependencies...maybe your work can address (or make obsolete) this issue too.

**Comment by aalfonsi** [comment] 2023-02-07 19:02
Few others dependencies (mostly optionals).

**Comment by joshua-cogliati-inl** [comment] 2023-02-07 19:11
Hm, can you include the errors you get from the other dependencies? (or does it fail to solve for them)?

**Comment by aalfonsi** [comment] 2023-02-07 19:52
With optional libraries:

```
... Installing libraries ...
... Installing libraries from conda-forge ...
... conda-forge command: conda create --name usnc_plugin -y -c conda-forge h5py numpy=1.21 scipy=1.7 scikit-learn=1.0 pandas=1.3 xarray=0.19 netcdf4=1.5 matplotlib=3.5.3 statsmodels=0.13 cloudpickle=2.2 tensorflow=2.9 python=3.9 hdf5 swig pylint coverage lxml psutil pip importlib_metadata pyside2 cmake imageio=2.22 line_profiler pywavelets=1.1 fmpy pyomo=6.4 glpk ipopt cyipopt setuptools
Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - cyipopt

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://conda.software.inl.gov/public/osx-arm64
  - https://conda.software.inl.gov/public/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

**Comment by joshua-cogliati-inl** [comment] 2023-02-07 19:54
Ah, osx-arm64.  Does this work if you force python to be a different version? (For osx-arm64 I have used the x86_64 version instead because of problems like this (which will need to be fixed at somepoint.)))

**Comment by joshua-cogliati-inl** [comment] 2023-02-17 17:26
After updating Numpy, xarray and matplotlib, osx-arm64 with conda at least sorta works (as in I got some test failures, but it did manage to successfully run establish conda and build raven).  So I would recommend trying again with devel.

I couldn't get a pip install to work on Mac OS with arm because it couldn't install tensorflow. (As of tensorflow 2.11 it only supports arm 64 on linux: https://pypi.org/project/tensorflow/#files )

**Comment by wangcj05** [comment] 2023-05-25 22:36
Let's try to support python 3.9 or higher in our next release @joshua-cogliati-inl

**Comment by PaulTalbot-INL** [comment] 2023-10-24 20:21
The python version was explicitly updated to 3.10 in https://github.com/idaholab/raven/pull/2197. Closing.

**Closed by PaulTalbot-INL** 2023-10-24 20:21 UTC
Labels: priority_normal, defect, RAVENv3.0

**Comment by alfoa** [comment] 2023-11-15 23:32
> The python version was explicitly updated to 3.10 in #2197. Closing.

@PaulTalbot-INL @wangcj05 @joshua-cogliati-inl The issue is in MAC/Linux not in Windows. For MAC/Linux, the dependencies file still reports:
``` <python skip_check='True' os='mac,linux'>3</python>```

**Comment by joshua-cogliati-inl** [comment] 2023-11-20 15:24
> > The python version was explicitly updated to 3.10 in #2197. Closing.
> 
> @PaulTalbot-INL @wangcj05 @joshua-cogliati-inl The issue is in MAC/Linux not in Windows. For MAC/Linux, the dependencies file still reports: ` <python skip_check='True' os='mac,linux'>3</python>`

Hm, I think part of the problem is we don't have a way to say Python 3.9 and 3.10 in the dependencies file.
